development:
  access_key_id: AKIAI5YYCGVRB5WQZ6DQ
  secret_access_key: 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
  bucket: membership_dev
test:
  access_key_id: AKIAI5YYCGVRB5WQZ6DQ
  secret_access_key: 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
  bucket: membership_test
production:
  access_key_id: AKIAI5YYCGVRB5WQZ6DQ
  secret_access_key: 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
  bucket: membership_prod