Feature: Membership Application
  As a member of the public
  I want to fill out an application
  In order to become a member of the organization
  
  Scenario: Filling out an application
    Given I am on the application page
    When I fill in "Name (Last)" with "Vizitei"
      And I fill in "(First)" with "Ethan"
      And I fill in "M.I." with "C"
      And I fill in "Social Security Number" with "123-45-6789"
      And I fill in "Address: (Street)" with "123 a street"
      And I fill in "(City)" with "Columbia"
      And I fill in "(State)" with "Mo"
      And I fill in "(Zip)" with "65203"
      And I fill in "Telephone Number: (Primary)" with "555-123-5678"
      And I fill in "(Secondary)" with "665-123-9067"
      And I fill in "E-mail:" with "ethan.vizitei@gmail.com"
      And I choose "membership_application_may_contact_at_work_true"
      And I fill in "Date of Birth:" with "08/09/1986"
      And I choose "membership_application_has_been_employed_under_alias_true"
      And I fill in "List Name(s):" with "E-Z-V, Viz"
      And I fill in "Driver's License Number:" with "L133244355466"
      And I fill in "State:" with "MO"
      And I fill in "Date of Expiration:" with "9/12/2013"
      And I choose "membership_application_has_crime_convictions_false"
      And I fill in "membership_application_crime_details" with ""
      And I choose "membership_application_has_traffic_violations_true"
      And I fill in "membership_application_traffic_violations_details" with "one pov fender bender"
      And I fill in "membership_application_employer_name" with "research 2 practice"
      And I fill in "membership_application_employer_phone" with "123-456-9876"
      And I fill in "membership_application_employer_start" with "3/12/2008"
      And I fill in "membership_application_employer_stop" with "5/15/2010"
      And I fill in "membership_application_employer_exit_reason" with "Not Yet"
      And I fill in "membership_application_employer_name_2" with "research 2 practice"
      And I fill in "membership_application_employer_phone_2" with "123-456-9876"
      And I fill in "membership_application_employer_start_2" with "3/12/2008"
      And I fill in "membership_application_employer_stop_2" with "5/15/2010"
      And I fill in "membership_application_employer_exit_reason_2" with "Not Yet"
      And I fill in "membership_application_employer_name_3" with "research 2 practice"
      And I fill in "membership_application_employer_phone_3" with "123-456-9876"
      And I fill in "membership_application_employer_start_3" with "3/12/2008"
      And I fill in "membership_application_employer_stop_3" with "5/15/2010"
      And I fill in "membership_application_employer_exit_reason_3" with "Not Yet"
      And I fill in "Branch:" with "Air Force"
      And I fill in "Rank at Discharge:" with "Sergent"
      And I fill in "Start Date:" with "08/01/2004"
      And I fill in "Discharge Date:" with "08/01/2010"
      And I fill in "Duties/Special Training:" with "things I did"
      And I fill in "Branch:" with "Air Force"
      And I fill in "Rank at Discharge:" with "Sergent"
      And I fill in "Start Date:" with "08/01/2004"
      And I fill in "Discharge Date:" with "08/01/2010"
      And I fill in "Duties/Special Training:" with "things I did"
      And I fill in "membership_application_college_name" with "Truman"
      And I fill in "membership_application_college_location" with "Kirksville, MO"
      And I fill in "membership_application_college_start_date" with "8/16/2004"
      And I fill in "membership_application_college_stop_date" with "3/15/2008"
      And I fill in "membership_application_college_units_completed" with "40"
      And I fill in "membership_application_college_major" with "Computer Science"
      And I fill in "membership_application_college_degree" with "Bachelors"
      And I fill in "membership_application_college_year" with "Junior"
      And I fill in "membership_application_college_name_2" with "Truman"
      And I fill in "membership_application_college_location_2" with "Kirksville, MO"
      And I fill in "membership_application_college_units_completed_2" with "40"
      And I fill in "membership_application_college_start_date_2" with "8/16/2004"
      And I fill in "membership_application_college_stop_date_2" with "3/15/2008"
      And I fill in "membership_application_college_major_2" with "Computer Science"
      And I fill in "membership_application_college_degree_2" with "Bachelors"
      And I fill in "membership_application_college_year_2" with "Junior"
      And I fill in "membership_application_college_name_3" with "Truman"
      And I fill in "membership_application_college_location_3" with "Kirksville, MO"
      And I fill in "membership_application_college_units_completed_3" with "40"
      And I fill in "membership_application_college_start_date_3" with "8/16/2004"
      And I fill in "membership_application_college_stop_date_3" with "3/15/2008"
      And I fill in "membership_application_college_major_3" with "Computer Science"
      And I fill in "membership_application_college_degree_3" with "Bachelors"
      And I fill in "membership_application_college_year_3" with "Junior"
      And I fill in "membership_application_training_institution" with "School name"
      And I fill in "membership_application_training_course" with "Class 1"
      And I fill in "membership_application_training_start_date" with "08/09/1986"
      And I fill in "membership_application_training_stop_date" with "09/08/1990"
      And I fill in "membership_application_training_hours" with "54"
      And I fill in "membership_application_training_institution_2" with "Other School"
      And I fill in "membership_application_training_course_2" with "Class 2"
      And I fill in "membership_application_training_start_date_2" with "07/13/2001"
      And I fill in "membership_application_training_stop_date_2" with "07/15/2001"
      And I fill in "membership_application_training_hours_2" with "12"
      And I fill in "membership_application_certification_name" with "cert 1"
      And I fill in "membership_application_certification_number" with "1234"
      And I fill in "membership_application_certification_issuer" with "BCFPD"
      And I fill in "membership_application_certification_expiration" with "08/09/2011"
      And I fill in "membership_application_certification_name_2" with "cert 2"
      And I fill in "membership_application_certification_number_2" with "4321"
      And I fill in "membership_application_certification_issuer_2" with "CFD"
      And I fill in "membership_application_certification_expiration_2" with "06/12/2012"
      And I fill in "membership_application_certification_name_3" with "cert 3"
      And I fill in "membership_application_certification_number_3" with "6543"
      And I fill in "membership_application_certification_issuer_3" with "EMS"
      And I fill in "membership_application_certification_expiration_3" with "09/12/4005"
      And I press "Submit"
    Then I should see "Thanks for your application!"